import assert from "node:assert/strict"
import { readFileSync } from "node:fs"

const shell = readFileSync("components/admin/page-settings-form.tsx", "utf8")
const actions = readFileSync("app/admin/cms-actions.ts", "utf8")
const city = readFileSync("components/admin/city-base-form.tsx", "utf8")
const country = readFileSync("components/admin/country-base-form.tsx", "utf8")
const protectedLayout = readFileSync("app/admin/(protected)/layout.tsx", "utf8")
const dirtyProvider = readFileSync("components/admin/admin-dirty-provider.tsx", "utf8")
const unsavedDialog = readFileSync("components/admin/unsaved-changes-dialog.tsx", "utf8")
const guardedLink = readFileSync("components/admin/guarded-link.tsx", "utf8")
const guardedRouter = readFileSync("components/admin/use-guarded-router.ts", "utf8")
const adminNav = readFileSync("components/admin/admin-nav.tsx", "utf8")
const saveState = readFileSync("lib/admin-save-state.ts", "utf8")
const draftCoordinator = readFileSync("components/admin/draft-coordinator.ts", "utf8")
assert.match(saveState, /AdminFieldError[\s\S]*AdminSaveResult[\s\S]*partial/, "shared save result exposes structured failures")
assert.match(draftCoordinator, /DraftContributor[\s\S]*validate\?[\s\S]*append\?[\s\S]*save\?[\s\S]*commitBaseline[\s\S]*reset/, "draft contributor supports validation, aggregate and independent saves")
assert.match(draftCoordinator, /if \(contributor\.append && contributor\.save\)/, "registry rejects ambiguous append plus save contributors")
assert.match(draftCoordinator, /this\.contributors\.get\(contributor\.id\) === contributor/, "stale cleanup cannot remove a newer registration")
assert.match(shell, /registerDraft[\s\S]*requestSave[\s\S]*saving/, "page settings context exposes the draft coordinator contract")
assert.doesNotMatch(shell, /registerStandaloneForm|standaloneSubmits/, "fire-and-forget compatibility API is removed")
assert.doesNotMatch(shell, /requestSubmit\(\)[\s\S]{0,120}return \{ ok: true \}/, "requestSubmit is never treated as awaited success")
assert.match(shell, /const submitted = new FormData\(form\)[\s\S]*append\?\.\(submitted\)[\s\S]*validateSettingsAction\(submitted\)[\s\S]*saveAction\(null, submitted\)/, "appended FormData is validated and submitted without replacement")
assert.match(shell, /const pageResult = await saveAction\(null, submitted\)[\s\S]*for \(const contributor of contributors\)[\s\S]*await contributor\.save\(\)/, "independent child saves run only after successful page action")
assert.match(shell, /savePromise\.current[\s\S]*partial:[\s\S]*commitBaseline/, "pipeline locks, reports partial saves, and commits baselines")
assert.match(shell, /savedSourceIds\.push\(contributor\.id\)[\s\S]{0,500}contributors\.forEach\(\(item\) => item\.commitBaseline\(\)\)/, "baselines commit only AFTER independent child saves succeed and all savedSourceIds are accumulated (validation → aggregate save → child saves → commitBaseline order)")
assert.match(shell, /dirtySaveLabel[\s\S]*Сохранить · 1 изменение[\s\S]*изменения[\s\S]*изменений/, "save button label pluralizes dirty areas correctly")
assert.match(shell, /const dirtyCount = useMemo\([\s\S]*nativeFormDirty[\s\S]*draftRegistry\.current\.snapshot\(\)\.filter/, "dirty count aggregates main form + all dirty contributors")
assert.match(shell, /function handleReset\(\) \{[\s\S]*formRef\.current\?\.reset\(\)[\s\S]*setNativeFormDirty\(false\)[\s\S]*for \(const contributor of all\) contributor\.reset\(\)[\s\S]*setDirty\(false\)[\s\S]*setState\(null\)[\s\S]*setPipelineError\(null\)/, "Cancel/Reset resets the native form, all contributor baselines, dirty flags, and error banners atomically")
assert.match(shell, /beforeunload/, "dirty forms warn before navigation")
assert.match(shell, /aria-invalid[\s\S]*scrollIntoView[\s\S]*focus/, "server errors reveal and focus a field")
assert.doesNotMatch(shell, /router\.refresh\(\)[\s\S]{0,200}commitBaseline\(\)/, "no router.refresh runs before all child saves succeed")
assert.match(actions, /Проверьте поле «Описание страницы»/)
assert.doesNotMatch(actions, /Описание страницы \(\$\{key\}\)/, "raw CMS key is never user-facing")
assert.doesNotMatch(city, /saveCityBaseAction|registerStandaloneForm/)
assert.doesNotMatch(country, /saveCountryBaseAction|registerStandaloneForm/)
assert.match(protectedLayout, /<AdminDirtyProvider>[\s\S]*<AdminNav/, "protected layout owns the dirty provider")
assert.match(dirtyProvider, /beforeunload/, "provider guards full-document exits")
assert.match(dirtyProvider, /pendingResolver/, "provider deduplicates concurrent dialogs")
assert.match(guardedLink, /onNavigate/, "GuardedLink guards Next SPA navigation")
assert.match(guardedLink, /target === ["']_blank["']|target !== ["']_self["']/, "new-tab links bypass confirmation")
assert.match(guardedLink, /hash/, "same-document hash navigation bypasses confirmation")
assert.match(guardedRouter, /push[\s\S]*replace[\s\S]*back/, "guarded router wraps route-changing methods")
assert.match(adminNav, /function NavLeafLink[\s\S]*<GuardedLink[\s\S]*href=\{item\.href\}/, "rendered admin leaves use GuardedLink")
assert.match(adminNav, /function Brand[\s\S]*<GuardedLink[\s\S]*href="\/admin"/, "rendered admin brand uses GuardedLink")
assert.match(adminNav, /confirmDiscard[\s\S]*logoutAction/, "logout consults dirty provider")
assert.doesNotMatch(adminNav, /onSubmit[\s\S]{0,500}requestSubmit/, "logout must not recursively submit itself")
assert.match(guardedLink, /await confirmDiscard\(\)[\s\S]*onNavigate\?\./, "caller onNavigate runs only after confirmation")
assert.match(unsavedDialog, /previouslyFocused/, "dialog restores focus")
assert.match(unsavedDialog, /Tab[\s\S]*focusable|focusable[\s\S]*Tab/, "dialog traps keyboard focus")
console.log("admin-save-draft-contract.selfcheck: ok")