import assert from "node:assert/strict"
import { readFileSync } from "node:fs"

const listing = readFileSync("components/site/tours-listing.tsx", "utf8")
const types = readFileSync("lib/types.ts", "utf8")
const schema = readFileSync("lib/db/schema.ts", "utf8")
const baselineMigration = readFileSync("drizzle/0000_talented_psylocke.sql", "utf8")
const server = readFileSync("lib/currencies-server.ts", "utf8")
const formatter = readFileSync("lib/currencies.ts", "utf8")
const adminForm = readFileSync("components/admin/currency-manager.tsx", "utf8")
const api = readFileSync("app/api/currencies/route.ts", "utf8")
const nbrb = readFileSync("lib/nbrb-rates.ts", "utf8")
const actions = readFileSync("app/admin/currency-actions.ts", "utf8")

assert.doesNotMatch(listing, /priceLabel|setPriceLabel|priceRanges\.map/, "broken legacy priceLabel dropdown must stay removed")
assert.match(listing, /currencies\.length \? currencies/, "tour listing must use server/admin currencies dynamically")
assert.match(listing, /options=\{currencyCodes\}/, "currency dropdown options must be derived from currency rows")
assert.match(listing, /value=\{currency\}/, "currency selector must display selected code, not symbol")
assert.match(listing, /currencySymbol=\{activeCurrency\.symbol \|\| activeCurrency\.code\}/, "price UI must receive admin currency symbol")

assert.match(types, /symbol: string/, "Currency type must expose symbol")
assert.match(schema, /symbol: text\("symbol"\)/, "currency schema must include symbol")
assert.match(baselineMigration, /"symbol" text/, "versioned baseline must create currency symbol")
assert.match(server, /symbol: row\.symbol\?\.trim\(\) \|\| defaultCurrencySymbol/, "server mapper must fallback symbols safely")
assert.match(formatter, /activeCurrency\.symbol \|\| activeCurrency\.code/, "price formatter must use symbol for displayed prices")
assert.match(formatter, /Math\.ceil\(amount\)/, "converted prices must always round upward")
const tourCard = readFileSync("components/site/tour-card.tsx", "utf8")
assert.match(tourCard, /initialCurrencyCode=\{currencyCode\}/, "tour card must pass the selected listing currency to PriceSwitcher")
assert.match(tourCard, /const fallbackPrice = price \?\? tour\.price/, "explicit listing price must win for legacy unstructured tours")
assert.match(adminForm, /name="symbol"/, "admin currencies form must edit symbol")
assert.match(api, /getCurrencies/, "/api/currencies must serve admin currencies")
assert.match(nbrb, /cache: "no-store"/, "manual NBRB refresh must not reuse a cached rate")
assert.match(nbrb, /AbortSignal\.timeout\(10_000\)/, "NBRB request must have a timeout")
assert.match(server, /skipped\.push\(code\)/, "missing USD or EUR must be reported individually")
assert.match(nbrb, /export async function fetchOfficialRates\(codes: string\[\]\)/, "NBRB client must accept all currency codes from the table")
assert.match(server, /rows\.filter\(\(row\) => !row\.isBase\)/, "refresh must target every non-base currency")
assert.match(server, /fetchOfficialRates\(targets\)/, "refresh must request the dynamic table currency list")
assert.match(server, /for \(const result of fetched\.rates\)/, "NBRB mapping must iterate fetched rate values")
assert.match(server, /const code = result\.code/, "NBRB mapping must use the uppercase ISO code from each result")
assert.doesNotMatch(server, /fetchOfficialUsdEur/, "currency refresh must not be hardcoded to USD and EUR")
assert.match(actions, /result\.updated} из \$\{result\.total/, "admin result must show the dynamic table currency count")
assert.match(adminForm, /всех небазовых валют из таблицы/, "admin UI must explain that all table currencies are refreshed")
assert.match(actions, /currency_refresh_nbrb/, "NBRB mutation must be written to admin audit")
assert.match(actions, /NBRB currency refresh failed/, "NBRB network errors must become visible action errors")
assert.match(adminForm, /Запрашиваем НБРБ и сохраняем курсы/, "admin UI must expose refresh progress")
assert.match(adminForm, /commercialRates/, "admin UI must expose refreshed values")
assert.match(nbrb, /rateForeignPerByn \* factor/, "markup must be added to the official converted rate")
assert.match(adminForm, /officialRates\[code\]/, "admin log must show the official rate before markup")
assert.match(adminForm, /markupAmounts\[code\]/, "admin log must show the added markup amount")

console.log("currency-integration.selfcheck: ok")
